name: tiny_fp
description: A tiny library for functional programming in dart
version: 0.1.0

author: Raman Verma <ramanverma4183@gmail.com>
homepage: https://github.com/maranix/tiny_fp
repository: https://github.com/maranix/tiny_fp
issue_tracker: https://github.com/maranix/tiny_fp/labels/tiny_fp

topics:
  - dart
  - utility
  - utils
  - extension
  - functional

environment:
  sdk: ^3.6.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.24.0
